sequences = ["""TTAGAGGTGCTTTCTCTCTGGACAGTTTTATGAATACATAAGGAGGTTCTGTCCCCACTCCC
TTCGCAACCGCATCTTATTGGTAATGAGCCAAAAAGATCATGTCTGAAATACAAGGAACG
GTTGAGTTTTCGGTAGAGCTACATAAATTTTATAATGTGGATCTCTTTCAGAGAGGGTAT
TACCAGATCCGAGTGACCTTGAAGGTGTCTTCAAGGATCCCCCACAGACTGAGTGCCTCC
ATCGCTGGGCAGACAGAGAGCAGCAGCCTGCATTCAGCC""", """CTGTGTCCATGACAGCACCGTG
CACAGCCGGGTCTTTCAGATCTTATACCGGAATGAAGAGGTACCCATAAATGATGCTGTG
GTCTTCCGAGTTCATTTACTCTTGGGTGGTGAAAGGATGGAAGACGCACTGAGTGAAGTA
GATTTTCAACTCAAGGTGGATCTGCACTTTACGGACAGTGAACAGCAGTTGAGGGATGTG
GCTGGGGCACCGATGGTCAGCAGCCGAACGCTTGGCCTGCACTTCCACCCCCGGAATGGT
CTGCACCACCAGGTCCCG"""]
print("Анализ последовательностей ДНК")
for seq in sequences:   
    print(f"\nПоследовательность: {seq}")
    print(f"Длина {len(seq)} нуклеотидов:")
    print(f"Построчный вывод:")
    for nucleotide in seq:
        print(f"\t{nucleotide}")
    print("\nЦикл выполнен!")